=== VijayEluri/flightbox/manifest/manifest.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manifest (events|channels)*>
<!ELEMENT channels (channel)*>
<!ELEMENT channel EMPTY>
<!ELEMENT events (event)*>
<!ELEMENT event (field)*>
<!ELEMENT field EMPTY>
<!ATTLIST manifest
   name    CDATA       #REQUIRED
   version CDATA       #REQUIRED
>
<!ATTLIST channel
   name    CDATA       #REQUIRED
>
<!ATTLIST event
   channel CDATA       #REQUIRED
   name    CDATA       #REQUIRED
>
<!ATTLIST field
   name    CDATA       #REQUIRED
   type    CDATA       #REQUIRED
>

=== VijayEluri/flightbox/tests/manifest/linux_pass_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifest SYSTEM "manifest.dtd">
<manifest name="linux_pass_metadata" version="1">
  <channels>
    <channel name="kernel"/>
  </channels>
  <events>
    <event channel="kernel" name="sched_schedule">
      <field name="prev_pid" type="uint64"/>
      <field name="next_pid" type="uint64"/>
      <field name="prev_state" type="uint64"/>
    </event>
    <event channel="kernel" name="syscall_entry">
      <field name="ip" type="uint64"/>
      <field name="syscall_id" type="uint64"/>
    </event>
    <event channel="kernel" name="syscall_exit">
      <field name="ret" type="uint64"/>
    </event>
  </events>
</manifest>

=== VijayEluri/flightbox/resources/manifest/linux-2.6.35.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifest SYSTEM "manifest.dtd">
<manifest name="linux" version="2.6.35">
  <channel name="kernel">
    <event name="sched_schedule">
        <field name="prev_pid" type="uint64"/>
        <field name="next_pid" type="uint64"/>
        <field name="prev_state" type="uint64"/>
    </event>
    <event channel="kernel" name="syscall_entry">
        <field name="ip" type="uint64"/>
        <field name="syscall_id" type="uint64"/>
    </event>
    <event channel="kernel" name="syscall_exit">
        <field name="ret" type="uint64"/>
    </event>
  </channel>
</manifest>
